import Head from "next/head";
import Image from "next/image";
import { SiteTitleWrapper } from "../styled-wrappers/SiteTitleWrapper.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SiteTitleWrapper>
        <h1>John William Davis</h1>
        <h2>Front End Developer</h2>
        <p className='special'>Portfolio</p>
        <span>Under Construction 🛠️</span>
      </SiteTitleWrapper>
    </div>
  );
}
